name: kazoo-configs-haproxy
base_branch: origin/4.3
base_core: null
template: spec.tmpl
package:
  centos7:
    name: kazoo-configs-haproxy
    group: Productivity/Telephony
    license: MPL1.1
    build_arch: noarch
    build_requires:
      - rpm-build
    summary: Kazoo specific configuration for HAProxy
    description: |
      The Kazoo platform uses HAProxy primarily to proxy connetcions
      to the database servers to ensure they are always reachable as
      well as load balance.  It is also used to proxy API, websockets
      and other services into Kazoo.  This package is the minimal
      configuration to ensure there are no single points of failure.
      If you need help you can contact us via the dev mailing
      list or on IRC at #2600hz on FreeNode.
    dist: .el7.centos
    requires:
      centos7:
         sudo: {}
    source: '%{_build_tar}'
    prep: '%setup -q'
    install: |
      mkdir -p %{buildroot}/etc/kazoo
      cp -r haproxy %{buildroot}/etc/kazoo
      cp CHANGELOG VERSION %{buildroot}/etc/kazoo/haproxy

      mkdir -p %{buildroot}/usr/sbin
      cp -r  system/sbin/* %{buildroot}/usr/sbin
      chmod +x %{buildroot}/usr/sbin/*

      mkdir -p %{buildroot}/etc/rsyslog.d
      rm -rf system/rsyslog.d/1-default-config-override.conf
      rm -rf system/rsyslog.d/5-rate-limits.conf
      cp -r  system/rsyslog.d/*.conf %{buildroot}/etc/rsyslog.d

      mkdir -p %{buildroot}/etc/logrotate.d
      cp -r  system/logrotate.d/*.conf %{buildroot}/etc/logrotate.d

      mkdir -p %{buildroot}/etc/security/limits.d
      cp -r  system/security/limits.d/*.conf %{buildroot}/etc/security/limits.d

      mkdir -p %{buildroot}/usr/lib/systemd/system
      cp system/systemd/* %{buildroot}/usr/lib/systemd/system
    files:
      doc:
        - CHANGELOG
        - VERSION
      config:
        - mode: noreplace
          path: /etc/kazoo/haproxy
        - mode: noreplace
          path: /etc/rsyslog.d/*haproxy*
        - mode: noreplace
          path: /etc/logrotate.d/*haproxy*
        - mode: noreplace
          path: /etc/security/limits.d/*haproxy*
      path:
        - /usr/sbin/kazoo-haproxy
        - /usr/lib/systemd/system/kazoo-haproxy.service
    url: 'http://www.2600hz.org'
    vendor: 2600Hz
metapackage:
  -
    name: meta-kazoo-haproxy
    package: kazoo-configs-haproxy
    type: required
    branch: '4.3'
